Remove unused field from QPA implementation
Silences a Clang++ warning/error:

> In file included from src/edf/qpa.cpp:12:
> include/edf/qpa.h:7:18: error: private field 'm' is not used [-Werror,-Wunused-private-field]
>     unsigned int m;
>                  ^
> 1 error generated.